import Footer from "@/components/Footer";
import ProductModalComp from "@/components/productmodal/ProductModalComp";

export const metadata = {
  title: "Product",
  description: "Generated by create next app",
};
export default function ProductModal() {
  return (
    <>
      <ProductModalComp />
      <Footer />
    </>
  );
}
